version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.9
  build:
    commands:
      - export BUCKET=codepipeline-us-east-1-588042790805
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml --debug
  post_build:
    commands:
      - ls
artifacts:
  type: zip
  files:
    - template.yaml
    - outputtemplate.yaml
    - buildspec.yml
